services:
  reverse-proxy:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    build: ./web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`) || Host(`prints.mayer.sh`)"

  service:
    build: ./service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service.rule=Host(`api.localhost`) || Host(`api.prints.mayer.sh`)"

  mariadb:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paas
      MYSQL_USER: user
      MYSQL_PASSWORD: password
