services:
  reverse-proxy:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    build: ./web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`) || Host(`prints.mayer.sh`)"
    environment:
      NUXT_PUBLIC_API_BASE_URL: http://api.localhost

  service:
    build: ./service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service.rule=Host(`api.localhost`) || Host(`api.prints.mayer.sh`)"
    # dynamically mount profile resources from resources/profiles
    #    volumes:
    #      - ./resources:/resources:ro
    environment:
      BASE_PRICE: 1
